version: '3.4'
services:

  my_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: mydb:latest
    container_name: my_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'social_media'
      MYSQL_ROOT_PASSWORD: 'pw'
      SERVICE_TAGS: case_twitter
      SERVICE_NAME: mysql
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    networks:
      - case_twitter_network

  collect_tweets:
    build:
      context: ./collect_tweets
      dockerfile: Dockerfile
    image: collect_tweets:latest
    container_name: collect_tweets
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: case_twitter
      SERVICE_NAME: collect_tweets
    volumes:
      - .:/usr/src/app
    networks:
      - case_twitter_network
    depends_on:
      - my_db

#Networks
networks:
  case_twitter_network:
    driver: bridge
# Volumes
volumes:
  dbdata: