version: '3.3'
services:

  my_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: mydb:latest
    container_name: my_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'social_media'
      MYSQL_ROOT_PASSWORD: 'pw'
      SERVICE_TAGS: case_twitter
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - case_twitter_network
#Networks
networks:
  case_twitter_network:
    driver: bridge
# Volumes
volumes:
  dbdata: